jaffle_shop:
  target: dev
  outputs:
    dev:
      type: postgres
      host: <host>
      user: <user>
      password: <password>
      port: 5432
      dbname: jaffle_shop
      schema: dbt_alice
      threads: 4